Repository OnAndOff-UMC/Backend, pull requests merged in 2024-02, with the labels that each got.

#41 [feat]: 서버 토큰 유효성 검증 API 구현
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/dto/LoginRequestDTO.java
  src/main/java/com/onnoff/onnoff/auth/jwt/dto/JwtToken.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/UserInterceptor.java
  src/main/java/com/onnoff/onnoff/auth/jwt/service/JwtTokenProvider.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/UserResponseDTO.java
Labels: :sparkles: feat

#39 [feat]: 푸시알람 구현
  .gitignore
  build.gradle
  src/main/java/com/onnoff/onnoff/OnnoffApplication.java
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/config/FirebaseConfig.java
  src/main/java/com/onnoff/onnoff/domain/push/controller/FcmController.java
  src/main/java/com/onnoff/onnoff/domain/push/dto/FcmServiceDto.java
  src/main/java/com/onnoff/onnoff/domain/push/dto/NotificationMessage.java
  src/main/java/com/onnoff/onnoff/domain/push/dto/NotificationType.java
  src/main/java/com/onnoff/onnoff/domain/push/service/FcmSendNotificationService.java
  src/main/java/com/onnoff/onnoff/domain/push/service/FcmService.java
  src/main/java/com/onnoff/onnoff/domain/user/User.java
  src/main/java/com/onnoff/onnoff/domain/user/repository/UserRepository.java
Labels: :sparkles: feat

#42 [feat]: 회고 관련 API 수정
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/controller/MemoirController.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/converter/MemoirConverter.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/dto/MemoirRequestDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/dto/MemoirResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/entity/Emoticon.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/entity/Memoir.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/repository/EmoticonRepository.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/repository/MemoirRepository.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/service/MemoirService.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/service/MemoirServiceImpl.java
Labels: :sparkles: feat, :truck: rename

#45 [refactor]: on API 수정
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/controller/ResolutionController.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/converter/ResolutionConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/dto/ResolutionRequest.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/dto/ResolutionResponse.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/repository/ResolutionRepository.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/service/ResolutionService.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/service/ResolutionServiceImpl.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/controller/OnController.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/controller/WorklogController.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/converter/OnConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/converter/WorklogConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/dto/OnResponse.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/dto/WorklogRequest.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/dto/WorklogResponse.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/repository/WorklogRepository.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/OnService.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/OnServiceImpl.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/WorklogService.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/WorklogServiceImpl.java
Labels: :recycle: refactor

#48 [feat]: 워라벨 피드 관련 API 수정
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/domain/off/feed/controller/FeedController.java
  src/main/java/com/onnoff/onnoff/domain/off/feed/converter/FeedConverter.java
  src/main/java/com/onnoff/onnoff/domain/off/feed/dto/FeedRequestDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/feed/dto/FeedResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/feed/entity/Feed.java
  src/main/java/com/onnoff/onnoff/domain/off/feed/service/FeedService.java
  src/main/java/com/onnoff/onnoff/domain/off/feed/service/FeedServiceImpl.java
Labels: :sparkles: feat, :truck: rename

#52 [fix]: 소셜 정보 조회 이름 조회 -> 닉네임 조회로 수정
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/kakao/KakaoOauth2DTO.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/resources/application.yml
Labels: :bug: fix, :test_tube: test

#51 [feat]: 통계 API 구현
  src/main/java/com/onnoff/onnoff/domain/off/feed/repository/FeedRepository.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/repository/MemoirAnswerRepository.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/repository/WorklogRepository.java
  src/main/java/com/onnoff/onnoff/domain/stats/controller/StatsController.java
  src/main/java/com/onnoff/onnoff/domain/stats/converter/StatsConverter.java
  src/main/java/com/onnoff/onnoff/domain/stats/dto/StatsResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/stats/service/StatsService.java
  src/main/java/com/onnoff/onnoff/domain/stats/service/StatsServiceImpl.java
Labels: :sparkles: feat

#53 [feat]: 워라벨 피드 사진 관련 API 수정
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/controller/FeedImageController.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/converter/FeedImageConverter.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/dto/FeedImageRequestDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/dto/FeedImageResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/entity/FeedImage.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/repository/FeedImageRepository.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/service/FeedImageService.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/service/FeedImageServiceImpl.java
  src/main/resources/application-dev.yml
Labels: :sparkles: feat, :truck: rename, :fire: remove

#55 [feat]: 회원가입 로직 수정
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/dto/LoginRequestDTO.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/domain/user/User.java
  src/main/java/com/onnoff/onnoff/domain/user/controller/InquiryEnumController.java
  src/main/java/com/onnoff/onnoff/domain/user/controller/UserController.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/EnumInquiryResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/UserResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/user/enums/ExperienceYear.java
  src/main/java/com/onnoff/onnoff/domain/user/enums/FieldOfWork.java
Labels: :sparkles: feat

#61 [feat]: 애플 로그인 구현
  .ebextensions_dev/00-makeFiles.config
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/service/AppleLoginService.java
  src/main/resources/application.yml
Labels: :sparkles: feat, :rocket: ci

#62 [fix]: 키 파일 절대 경로로 수정
  src/main/java/com/onnoff/onnoff/auth/service/AppleLoginService.java
  src/main/resources/application.yml
Labels: :bug: fix

#63 [style]: 테스트용 로그만 추가
  src/main/java/com/onnoff/onnoff/auth/service/AppleLoginService.java
Labels: :art: style

#65 [fix]: 액세스 토큰 발급 요청 수정
  src/main/java/com/onnoff/onnoff/auth/feignClient/client/AppleAuthClient.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/config/FeignConfig.java
  src/main/java/com/onnoff/onnoff/auth/service/AppleLoginService.java
Labels: :sparkles: feat, :bug: fix

#69 [fix]: 월별 통계 로직 수정
  src/main/java/com/onnoff/onnoff/domain/stats/service/StatsServiceImpl.java
Labels: :bug: fix

#72 [feat]: 닉네임 중복체크 API 구현
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/domain/user/controller/UserController.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/UserRequestDTO.java
  src/main/java/com/onnoff/onnoff/domain/user/repository/UserRepository.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserService.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserServiceImpl.java
Labels: :sparkles: feat

#70 [feat]: 회고 미리보기 조회 API 수정
  src/main/java/com/onnoff/onnoff/domain/off/memoir/converter/MemoirConverter.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/dto/MemoirResponseDTO.java
Labels: :sparkles: feat

#73 [feat]: 회원탈퇴 API 구현
  src/main/java/com/onnoff/onnoff/auth/config/FilterConfig.java
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/dto/LoginRequestDTO.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/client/AppleAuthClient.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/client/KakaoApiClient.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/apple/RevokeTokenReqeust.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/kakao/UnlinkRequest.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/auth/jwt/service/JwtTokenProvider.java
  src/main/java/com/onnoff/onnoff/auth/jwt/service/TokenProvider.java
  src/main/java/com/onnoff/onnoff/auth/service/AppleLoginService.java
  src/main/java/com/onnoff/onnoff/auth/service/KakaoLoginService.java
  src/main/java/com/onnoff/onnoff/domain/user/controller/UserController.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/EnumInquiryResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/user/enums/FieldOfWork.java
  src/main/java/com/onnoff/onnoff/domain/user/enums/SocialType.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserService.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserServiceImpl.java
  src/test/java/com/onnoff/onnoff/domain/user/service/UserServiceImplTest.java
Labels: :sparkles: feat, :test_tube: test

#75 [feat]: 회고 조회 관련 API 수정
  src/main/java/com/onnoff/onnoff/domain/off/memoir/controller/MemoirController.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/converter/MemoirConverter.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/dto/MemoirResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/service/MemoirService.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/service/MemoirServiceImpl.java
Labels: :sparkles: feat

#78 [feat]: 업무일지 조회 API 구현
  src/main/java/com/onnoff/onnoff/domain/on/worklog/controller/WorklogController.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/converter/WorklogConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/WorklogService.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/WorklogServiceImpl.java
Labels: :sparkles: feat

#82 [feat]: ON 관련 API 수정
  src/main/java/com/onnoff/onnoff/domain/on/resolution/converter/ResolutionConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/dto/ResolutionResponse.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/converter/OnConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/converter/WorklogConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/dto/WorklogResponse.java
Labels: :sparkles: feat

#84 [feat]: 회고 관련 API 수정
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/converter/MemoirConverter.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/dto/MemoirRequestDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/dto/MemoirResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/entity/Memoir.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/repository/MemoirAnswerRepository.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/service/MemoirServiceImpl.java
Labels: :sparkles: feat, :bug: fix, :recycle: refactor, :fire: remove

#80 [feat]: 회원가입 유효성 검증 추가, 닉네임 처리
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/dto/LoginRequestDTO.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/CustomErrorDecoder.java
  src/main/java/com/onnoff/onnoff/auth/service/KakaoLoginService.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserServiceImpl.java
Labels: :sparkles: feat, :bug: fix

#86 [fix]: 애플 요청 DTO 수정
  src/main/java/com/onnoff/onnoff/auth/dto/LoginRequestDTO.java
Labels: :bug: fix

#87 [fix]: 애플 요청 DTO 컨버터 수정
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
Labels: :bug: fix

#93 [refactor]: 유저 정보 수정 API 요청DTO, 응답DTO enum value로 변경
  src/main/java/com/onnoff/onnoff/domain/user/User.java
  src/main/java/com/onnoff/onnoff/domain/user/controller/UserController.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/UserRequestDTO.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/UserResponseDTO.java
Labels: :recycle: refactor

#96 [refactor]: 유저 조회 API 관련 수정
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/EnumInquiryResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/UserResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/user/enums/ExperienceYear.java
Labels: :recycle: refactor

#98 [feat]: 스왑 설정 파일 추가
  .ebextensions_dev/02-setup_swap.config
Labels: :sparkles: feat, :rocket: ci

#99 [ci]: 빌드 테스트 추가
  .github/workflows/dev_deploy.yml
Labels: :rocket: ci
