Repository OnAndOff-UMC/Backend, pull requests merged in 2024-01, with the labels that each got.

#5 [feat]: User 엔티티 생성 및 테스트
  build.gradle
  src/main/java/com/onnoff/onnoff/domain/user/User.java
  src/main/java/com/onnoff/onnoff/domain/user/enums/SocialType.java
  src/main/java/com/onnoff/onnoff/domain/user/enums/Status.java
  src/main/java/com/onnoff/onnoff/domain/user/repository/UserRepository.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserService.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserServiceImpl.java
  src/test/java/com/onnoff/onnoff/domain/user/service/UserServiceImplTest.java
Labels: :sparkles: feat, :test_tube: test

#6 [feat]: on 관련 엔티티 생성
  src/main/java/com/onnoff/onnoff/domain/on/resolution/entity/Resolution.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/entity/Worklog.java
Labels: :sparkles: feat

#9 [feat]: off 관련 entity 생성
  src/main/java/com/onnoff/onnoff/domain/off/feed/entity/Feed.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/entity/FeedImage.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/entity/Memoir.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/entity/MemoirAnswer.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/entity/MemoirQuestion.java
Labels: :sparkles: feat

#11 [feat]: apiPayload 작성 및 swagger 세팅
  build.gradle
  src/main/java/com/onnoff/onnoff/apiPayload/ApiResponse.java
  src/main/java/com/onnoff/onnoff/apiPayload/code/BaseCode.java
  src/main/java/com/onnoff/onnoff/apiPayload/code/BaseErrorCode.java
  src/main/java/com/onnoff/onnoff/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/onnoff/onnoff/apiPayload/code/ReasonDTO.java
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/onnoff/onnoff/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/onnoff/onnoff/apiPayload/exception/GeneralException.java
  src/main/java/com/onnoff/onnoff/domain/user/User.java
Labels: :sparkles: feat, :package: chore

#15 [feat]: 오늘의 회고 관련 API 구현
  build.gradle
  src/main/java/com/onnoff/onnoff/OnnoffApplication.java
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/controller/MemoirController.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/converter/MemoirConverter.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/dto/MemoirRequestDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/dto/MemoirResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/entity/Memoir.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/entity/MemoirAnswer.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/repository/MemoirAnswerRepository.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/repository/MemoirQuestionRepository.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/repository/MemoirRepository.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/service/MemoirService.java
  src/main/java/com/onnoff/onnoff/domain/off/memoir/service/MemoirServiceImpl.java
Labels: :sparkles: feat, :construction_worker: build

#14 [feat]: 카카오 소셜 로그인 토큰 검증 및 DB에 정보 저장
  build.gradle
  src/main/java/com/onnoff/onnoff/OnnoffApplication.java
  src/main/java/com/onnoff/onnoff/auth/client/KakaoApiClient.java
  src/main/java/com/onnoff/onnoff/auth/client/KakaoOauth2Client.java
  src/main/java/com/onnoff/onnoff/auth/client/config/LoggingConfiguration.java
  src/main/java/com/onnoff/onnoff/auth/client/dto/KakaoOauth2DTO.java
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/dto/LoginResponseDTO.java
  src/main/java/com/onnoff/onnoff/auth/service/LoginService.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/entity/Resolution.java
  src/main/java/com/onnoff/onnoff/domain/user/User.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/repository/UserRepository.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserService.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserServiceImpl.java
Labels: :sparkles: feat, :test_tube: test, :package: chore

#17 [feat]: 오늘의 다짐 API 구현
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/apiPayload/exception/handler/ResolutionHandler.java
  src/main/java/com/onnoff/onnoff/domain/common/BaseEntity.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/controller/ResolutionController.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/converter/ResolutionConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/dto/ResolutionRequest.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/dto/ResolutionResponse.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/entity/Resolution.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/repository/ResolutionRepository.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/service/ResolutionService.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/service/ResolutionServiceImpl.java
Labels: :sparkles: feat

#20 [feat]: 로그인 예외 처리 및 jwt 인증 기능 구현
  build.gradle
  src/main/java/com/onnoff/onnoff/OnnoffApplication.java
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/onnoff/onnoff/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/onnoff/onnoff/auth/UserContext.java
  src/main/java/com/onnoff/onnoff/auth/client/config/LoggingConfiguration.java
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/CustomErrorDecoder.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/client/KakaoApiClient.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/client/KakaoOauth2Client.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/config/FeignConfig.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/ErrorResponseDTO.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/KakaoOauth2DTO.java
  src/main/java/com/onnoff/onnoff/auth/jwt/dto/JwtToken.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/UserInterceptor.java
  src/main/java/com/onnoff/onnoff/auth/jwt/service/JwtTokenProvider.java
  src/main/java/com/onnoff/onnoff/auth/jwt/service/JwtUtil.java
  src/main/java/com/onnoff/onnoff/auth/service/LoginService.java
  src/main/java/com/onnoff/onnoff/config/SwaggerConfig.java
  src/main/java/com/onnoff/onnoff/domain/user/User.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/UserResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserService.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserServiceImpl.java
  src/main/resources/application.properties
Labels: :sparkles: feat, :test_tube: test, :package: chore

#21 [feat]: 워라벨 피드 사진 관련 API 구현
  build.gradle
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/config/AwsS3Config.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/controller/FeedImageController.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/converter/FeedImageConverter.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/dto/FeedImageRequestDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/dto/FeedImageResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/entity/FeedImage.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/repository/FeedImageRepository.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/service/FeedImageService.java
  src/main/java/com/onnoff/onnoff/domain/off/feedImage/service/FeedImageServiceImpl.java
Labels: :sparkles: feat, :construction_worker: build

#22 [fix]: 로그인 처리 로직 수정, JwtAuthfilter 적용 경로 수정
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/dto/LoginResponseDTO.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/client/KakaoApiClient.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/KakaoOauth2DTO.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/UserInterceptor.java
  src/main/java/com/onnoff/onnoff/auth/service/LoginService.java
  src/main/java/com/onnoff/onnoff/domain/user/User.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/dto/UserResponseDTO.java
Labels: :bug: fix

#19 refactor: dto 및 mapping 방법 수정
  src/main/java/com/onnoff/onnoff/domain/on/resolution/controller/ResolutionController.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/dto/ResolutionRequest.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/service/ResolutionService.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/service/ResolutionServiceImpl.java
Labels: :recycle: refactor

#26 [feat]: 업무일지 관련 API 구현
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/onnoff/onnoff/apiPayload/exception/handler/WorklogHandler.java
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/controller/ResolutionController.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/converter/ResolutionConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/resolution/service/ResolutionServiceImpl.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/controller/OnController.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/controller/WorklogController.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/converter/OnConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/converter/WorklogConverter.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/dto/OnResponse.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/dto/WorklogRequest.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/dto/WorklogResponse.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/entity/Worklog.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/repository/WorklogRepository.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/OnService.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/OnServiceImpl.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/WorklogService.java
  src/main/java/com/onnoff/onnoff/domain/on/worklog/service/WorklogServiceImpl.java
Labels: :sparkles: feat, :recycle: refactor

#33 [ci]: CI/CD 파이프라인 구축
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/com/onnoff/onnoff/auth/config/WebConfig.java
  src/main/java/com/onnoff/onnoff/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/onnoff/onnoff/domain/common/controller/RootController.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: :sparkles: feat, :rocket: ci

#34 [ci]: RDB URI 환경변수로 변경
  src/main/resources/application-dev.yml
Labels: :sparkles: feat, :rocket: ci

#35 [fix]: 환경 이름 변경
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#31 [feat]: 요일 관련 API 구현
  src/main/java/com/onnoff/onnoff/domain/weekday/controller/WeekdayController.java
  src/main/java/com/onnoff/onnoff/domain/weekday/dto/WeekdayResponseDTO.java
  src/main/java/com/onnoff/onnoff/domain/weekday/service/WeekdayService.java
  src/main/java/com/onnoff/onnoff/domain/weekday/service/WeekdayServiceImpl.java
Labels: :sparkles: feat

#28 [feat]: 애플 로그인 구현
  src/main/java/com/onnoff/onnoff/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
  src/main/java/com/onnoff/onnoff/auth/dto/LoginRequestDTO.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/CustomErrorDecoder.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/client/AppleAuthClient.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/client/KakaoApiClient.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/client/KakaoOauth2Client.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/JwkResponse.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/KakaoOauth2DTO.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/TokenResponse.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/apple/TokenRequest.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/kakao/ErrorResponseDTO.java
  src/main/java/com/onnoff/onnoff/auth/feignClient/dto/kakao/KakaoOauth2DTO.java
  src/main/java/com/onnoff/onnoff/auth/service/AppleLoginService.java
  src/main/java/com/onnoff/onnoff/auth/service/KakaoLoginService.java
  src/main/java/com/onnoff/onnoff/auth/service/LoginService.java
  src/main/java/com/onnoff/onnoff/auth/service/tokenValidator/SocialTokenValidator.java
  src/main/java/com/onnoff/onnoff/auth/service/tokenValidator/SocialTokenValidatorImpl.java
  src/main/java/com/onnoff/onnoff/domain/user/User.java
  src/main/java/com/onnoff/onnoff/domain/user/converter/UserConverter.java
  src/main/java/com/onnoff/onnoff/domain/user/repository/UserRepository.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserService.java
  src/main/java/com/onnoff/onnoff/domain/user/service/UserServiceImpl.java
  src/test/java/com/onnoff/onnoff/domain/user/service/UserServiceImplTest.java
Labels: :sparkles: feat, :recycle: refactor

#37 [fix]: redirectUri 수정
  src/main/java/com/onnoff/onnoff/auth/controller/LoginController.java
Labels: :bug: fix
